def marc_relators():
    """returns a dict of marc relators"""

    marc_relators = {"abridger":"abr",
        "nul_contributor":"nctb",
        "art copyist":"acp",
        "actor":"act",
        "art director":"adi",
        "adapter":"adp",
        "author of afterword, colophon, etc.":"aft",
        "analyst":"anl",
        "animator":"anm",
        "annotator":"ann",
        "bibliographic antecedent":"ant",
        "appellee":"ape",
        "appellant":"apl",
        "applicant":"app",
        "author in quotations or text abstracts":"aqt",
        "architect":"arc",
        "artistic director":"ard",
        "arranger":"arr",
        "artist":"art",
        "assignee":"asg",
        "associated name":"asn",
        "autographer":"ato",
        "attributed name":"att",
        "auctioneer":"auc",
        "author of dialog":"aud",
        "author of introduction, etc.":"aui",
        "screenwriter":"aus",
        "author":"aut",
        "binding designer":"bdd",
        "bookjacket designer":"bjd",
        "book designer":"bkd",
        "book producer":"bkp",
        "blurb writer":"blw",
        "binder":"bnd",
        "bookplate designer":"bpd",
        "broadcaster":"brd",
        "braille embosser":"brl",
        "bookseller":"bsl",
        "caster":"cas",
        "conceptor":"ccp",
        "choreographer":"chr",
        "collaborator":"-clb",
        "client":"cli",
        "calligrapher":"cll",
        "colorist":"clr",
        "collotyper":"clt",
        "commentator":"cmm",
        "composer":"cmp",
        "compositor":"cmt",
        "conductor":"cnd",
        "cinematographer":"cng",
        "censor":"cns",
        "contestant-appellee":"coe",
        "collector":"col",
        "compiler":"com",
        "conservator":"con",
        "collection registrar":"cor",
        "contestant":"cos",
        "contestant-appellant":"cot",
        "court governed":"cou",
        "cover designer":"cov",
        "copyright claimant":"cpc",
        "complainant-appellee":"cpe",
        "copyright holder":"cph",
        "complainant":"cpl",
        "complainant-appellant":"cpt",
        "creator":"cre",
        "correspondent":"crp",
        "corrector":"crr",
        "court reporter":"crt",
        "consultant":"csl",
        "consultant to a project":"csp",
        "costume designer":"cst",
        "contributor":"ctb",
        "contestee-appellee":"cte",
        "cartographer":"ctg",
        "contractor":"ctr",
        "contestee":"cts",
        "contestee-appellant":"ctt",
        "curator":"cur",
        "commentator for written text":"cwt",
        "distribution place":"dbp",
        "defendant":"dfd",
        "defendant-appellee":"dfe",
        "defendant-appellant":"dft",
        "degree granting institution":"dgg",
        "degree supervisor":"dgs",
        "dissertant":"dis",
        "delineator":"dln",
        "dancer":"dnc",
        "donor":"dnr",
        "depicted":"dpc",
        "depositor":"dpt",
        "draftsman":"drm",
        "director":"drt",
        "designer":"dsr",
        "distributor":"dst",
        "data contributor":"dtc",
        "dedicatee":"dte",
        "data manager":"dtm",
        "dedicator":"dto",
        "dubious author":"dub",
        "editor of compilation":"edc",
        "editor of moving image work":"edm",
        "editor":"edt",
        "engraver":"egr",
        "electrician":"elg",
        "electrotyper":"elt",
        "engineer":"eng",
        "enacting jurisdiction":"enj",
        "etcher":"etr",
        "event place":"evp",
        "expert":"exp",
        "facsimilist":"fac",
        "film distributor":"fds",
        "field director":"fld",
        "film editor":"flm",
        "film director":"fmd",
        "filmmaker":"fmk",
        "former owner":"fmo",
        "film producer":"fmp",
        "funder":"fnd",
        "first party":"fpy",
        "forger":"frg",
        "geographic information specialist":"gis",
        "graphic technician":"-grt",
        "host institution":"his",
        "honoree":"hnr",
        "host":"hst",
        "illustrator":"ill",
        "illuminator":"ilu",
        "inscriber":"ins",
        "inventor":"inv",
        "issuing body":"isb",
        "instrumentalist":"itr",
        "interviewee":"ive",
        "interviewer":"ivr",
        "judge":"jud",
        "jurisdiction governed":"jug",
        "laboratory":"lbr",
        "librettist":"lbt",
        "laboratory director":"ldr",
        "lead":"led",
        "libelee-appellee":"lee",
        "libelee":"lel",
        "lender":"len",
        "libelee-appellant":"let",
        "lighting designer":"lgd",
        "libelant-appellee":"lie",
        "libelant":"lil",
        "libelant-appellant":"lit",
        "landscape architect":"lsa",
        "licensee":"lse",
        "licensor":"lso",
        "lithographer":"ltg",
        "lyricist":"lyr",
        "music copyist":"mcp",
        "metadata contact":"mdc",
        "medium":"med",
        "manufacture place":"mfp",
        "manufacturer":"mfr",
        "moderator":"mod",
        "monitor":"mon",
        "marbler":"mrb",
        "markup editor":"mrk",
        "musical director":"msd",
        "metal-engraver":"mte",
        "minute taker":"mtk",
        "musician":"mus",
        "narrator":"nrt",
        "opponent":"opn",
        "originator":"org",
        "organizer":"orm",
        "onscreen presenter":"osp",
        "other":"oth",
        "owner":"own",
        "panelist":"pan",
        "patron":"pat",
        "publishing director":"pbd",
        "publisher":"pbl",
        "project director":"pdr",
        "proofreader":"pfr",
        "photographer":"pht",
        "platemaker":"plt",
        "permitting agency":"pma",
        "production manager":"pmn",
        "printer of plates":"pop",
        "papermaker":"ppm",
        "puppeteer":"ppt",
        "praeses":"pra",
        "process contact":"prc",
        "production personnel":"prd",
        "presenter":"pre",
        "performer":"prf",
        "programmer":"prg",
        "printmaker":"prm",
        "production company":"prn",
        "producer":"pro",
        "production place":"prp",
        "production designer":"prs",
        "printer":"prt",
        "provider":"prv",
        "patent applicant":"pta",
        "plaintiff-appellee":"pte",
        "plaintiff":"ptf",
        "patent holder":"pth",
        "plaintiff-appellant":"ptt",
        "publication place":"pup",
        "rubricator":"rbr",
        "recordist":"rcd",
        "recording engineer":"rce",
        "addressee":"rcp",
        "radio director":"rdd",
        "redaktor":"red",
        "renderer":"ren",
        "researcher":"res",
        "reviewer":"rev",
        "radio producer":"rpc",
        "repository":"rps",
        "reporter":"rpt",
        "responsible party":"rpy",
        "respondent-appellee":"rse",
        "restager":"rsg",
        "respondent":"rsp",
        "restorationist":"rsr",
        "respondent-appellant":"rst",
        "research team head":"rth",
        "research team member":"rtm",
        "scientific advisor":"sad",
        "scenarist":"sce",
        "sculptor":"scl",
        "scribe":"scr",
        "sound designer":"sds",
        "secretary":"sec",
        "stage director":"sgd",
        "signer":"sgn",
        "supporting host":"sht",
        "seller":"sll",
        "singer":"sng",
        "speaker":"spk",
        "sponsor":"spn",
        "second party":"spy",
        "surveyor":"srv",
        "set designer":"std",
        "setting":"stg",
        "storyteller":"stl",
        "stage manager":"stm",
        "standards body":"stn",
        "stereotyper":"str",
        "technical director":"tcd",
        "teacher":"tch",
        "thesis advisor":"ths",
        "television director":"tld",
        "television producer":"tlp",
        "transcriber":"trc",
        "translator":"trl",
        "type designer":"tyd",
        "typographer":"tyg",
        "university place":"uvp",
        "voice actor":"vac",
        "videographer":"vdg",
        "writer of added commentary":"wac",
        "writer of added lyrics":"wal",
        "writer of accompanying material":"wam",
        "writer of added text":"wat",
        "woodcutter":"wdc",
        "wood engraver":"wde",
        "writer of introduction":"win",
        "witness":"wit",
        "writer of preface":"wpr",
        "writer of supplementary textual content":"wst"
    }
    return marc_relators
